/**
 * WARNING
 * THIS FILE WAS AUTO GENERATED FROM Node.js [/scripts/icon-generator.js]
 * DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
 * Update Time: 2019-2-1 15:31:17
 **/

import { SVGProps, FunctionComponent } from 'react';

import { ReactComponent as SVGRCaretDown } from '../../assets/icon/caret-down.svg';
import { ReactComponent as SVGRCheck } from '../../assets/icon/check.svg';
import { ReactComponent as SVGRCheckCircle } from '../../assets/icon/check-circle.svg';
import { ReactComponent as SVGRClose } from '../../assets/icon/close.svg';
import { ReactComponent as SVGRCloseCircle } from '../../assets/icon/close-circle.svg';
import { ReactComponent as SVGRExclamation } from '../../assets/icon/exclamation.svg';
import { ReactComponent as SVGRExclamationCircle } from '../../assets/icon/exclamation-circle.svg';
import { ReactComponent as SVGRInfo } from '../../assets/icon/info.svg';
import { ReactComponent as SVGRInfoCircle } from '../../assets/icon/info-circle.svg';
import { ReactComponent as SVGRLoading } from '../../assets/icon/loading.svg';
import { ReactComponent as SVGRMinus } from '../../assets/icon/minus.svg';
import { ReactComponent as SVGRPlus } from '../../assets/icon/plus.svg';
import { ReactComponent as SVGRWarning } from '../../assets/icon/warning.svg';

type SVGR = FunctionComponent<SVGProps<SVGSVGElement>>;

export interface Sheet {
  ['caret-down']: SVGR;
  ['check']: SVGR;
  ['check-circle']: SVGR;
  ['close']: SVGR;
  ['close-circle']: SVGR;
  ['exclamation']: SVGR;
  ['exclamation-circle']: SVGR;
  ['info']: SVGR;
  ['info-circle']: SVGR;
  ['loading']: SVGR;
  ['minus']: SVGR;
  ['plus']: SVGR;
  ['warning']: SVGR;
}

export type IconType = keyof Sheet;

export let iconSheet: Sheet = {
  ['caret-down']: SVGRCaretDown,
  ['check']: SVGRCheck,
  ['check-circle']: SVGRCheckCircle,
  ['close']: SVGRClose,
  ['close-circle']: SVGRCloseCircle,
  ['exclamation']: SVGRExclamation,
  ['exclamation-circle']: SVGRExclamationCircle,
  ['info']: SVGRInfo,
  ['info-circle']: SVGRInfoCircle,
  ['loading']: SVGRLoading,
  ['minus']: SVGRMinus,
  ['plus']: SVGRPlus,
  ['warning']: SVGRWarning
};

export let iconList: IconType[] = [
  'caret-down',
  'check',
  'check-circle',
  'close',
  'close-circle',
  'exclamation',
  'exclamation-circle',
  'info',
  'info-circle',
  'loading',
  'minus',
  'plus',
  'warning'
];
