/**
 * WARNING
 * THIS FILE WAS AUTO GENERATED FROM Node.js [/scripts/icon-generator.js]
 * DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
 * Update Time: 2019-7-16 2:34:46 PM
 **/

import { SVGProps, FunctionComponent } from 'react'

import { ReactComponent as SVGRCalendar } from '../../assets/icon/application/calendar.svg'
import { ReactComponent as SVGRCaretDown } from '../../assets/icon/directional/caret-down.svg'
import { ReactComponent as SVGRCaretLeft } from '../../assets/icon/directional/caret-left.svg'
import { ReactComponent as SVGRCaretRight } from '../../assets/icon/directional/caret-right.svg'
import { ReactComponent as SVGRCaretUp } from '../../assets/icon/directional/caret-up.svg'
import { ReactComponent as SVGRCheck } from '../../assets/icon/suggested/check.svg'
import { ReactComponent as SVGRCheckCircle } from '../../assets/icon/suggested/check-circle.svg'
import { ReactComponent as SVGRClose } from '../../assets/icon/suggested/close.svg'
import { ReactComponent as SVGRCloseCircle } from '../../assets/icon/suggested/close-circle.svg'
import { ReactComponent as SVGRConfirm } from '../../assets/icon/suggested/confirm.svg'
import { ReactComponent as SVGRDown } from '../../assets/icon/directional/down.svg'
import { ReactComponent as SVGRError } from '../../assets/icon/suggested/error.svg'
import { ReactComponent as SVGRExclamation } from '../../assets/icon/suggested/exclamation.svg'
import { ReactComponent as SVGRExclamationCircle } from '../../assets/icon/suggested/exclamation-circle.svg'
import { ReactComponent as SVGRGithub } from '../../assets/icon/brand/github.svg'
import { ReactComponent as SVGRInfo } from '../../assets/icon/suggested/info.svg'
import { ReactComponent as SVGRInfoCircle } from '../../assets/icon/suggested/info-circle.svg'
import { ReactComponent as SVGRLeft } from '../../assets/icon/directional/left.svg'
import { ReactComponent as SVGRLoading } from '../../assets/icon/application/loading.svg'
import { ReactComponent as SVGRMinus } from '../../assets/icon/suggested/minus.svg'
import { ReactComponent as SVGRPlus } from '../../assets/icon/suggested/plus.svg'
import { ReactComponent as SVGRQuestion } from '../../assets/icon/suggested/question.svg'
import { ReactComponent as SVGRQuestionCircle } from '../../assets/icon/suggested/question-circle.svg'
import { ReactComponent as SVGRRight } from '../../assets/icon/directional/right.svg'
import { ReactComponent as SVGRUp } from '../../assets/icon/directional/up.svg'
import { ReactComponent as SVGRWarning } from '../../assets/icon/suggested/warning.svg'

type SVGR = FunctionComponent<SVGProps<SVGSVGElement>>

export interface Sheet {
  ['calendar']: SVGR
  ['caret-down']: SVGR
  ['caret-left']: SVGR
  ['caret-right']: SVGR
  ['caret-up']: SVGR
  ['check']: SVGR
  ['check-circle']: SVGR
  ['close']: SVGR
  ['close-circle']: SVGR
  ['confirm']: SVGR
  ['down']: SVGR
  ['error']: SVGR
  ['exclamation']: SVGR
  ['exclamation-circle']: SVGR
  ['github']: SVGR
  ['info']: SVGR
  ['info-circle']: SVGR
  ['left']: SVGR
  ['loading']: SVGR
  ['minus']: SVGR
  ['plus']: SVGR
  ['question']: SVGR
  ['question-circle']: SVGR
  ['right']: SVGR
  ['up']: SVGR
  ['warning']: SVGR
}

export type IconType = keyof Sheet

export let iconSheet: Sheet = {
  ['calendar']: SVGRCalendar,
  ['caret-down']: SVGRCaretDown,
  ['caret-left']: SVGRCaretLeft,
  ['caret-right']: SVGRCaretRight,
  ['caret-up']: SVGRCaretUp,
  ['check']: SVGRCheck,
  ['check-circle']: SVGRCheckCircle,
  ['close']: SVGRClose,
  ['close-circle']: SVGRCloseCircle,
  ['confirm']: SVGRConfirm,
  ['down']: SVGRDown,
  ['error']: SVGRError,
  ['exclamation']: SVGRExclamation,
  ['exclamation-circle']: SVGRExclamationCircle,
  ['github']: SVGRGithub,
  ['info']: SVGRInfo,
  ['info-circle']: SVGRInfoCircle,
  ['left']: SVGRLeft,
  ['loading']: SVGRLoading,
  ['minus']: SVGRMinus,
  ['plus']: SVGRPlus,
  ['question']: SVGRQuestion,
  ['question-circle']: SVGRQuestionCircle,
  ['right']: SVGRRight,
  ['up']: SVGRUp,
  ['warning']: SVGRWarning
}
