/**
 * WARNING
 * THIS FILE WAS AUTO GENERATED FROM Node.js [/scripts/icon-generator.js]
 * DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
 * Update Time: 2019-7-16 2:34:46 PM
 **/

import { IconType } from './icon-sheet-generated'

interface IconListType {
  group: string
  children: IconType[]
}

export let iconList: IconListType[] = [
  { group: 'application', children: ['calendar', 'loading'] },
  { group: 'brand', children: ['github'] },
  {
    group: 'directional',
    children: [
      'caret-down',
      'caret-left',
      'caret-right',
      'caret-up',
      'down',
      'left',
      'right',
      'up'
    ]
  },
  {
    group: 'suggested',
    children: [
      'check-circle',
      'check',
      'close-circle',
      'close',
      'confirm',
      'error',
      'exclamation-circle',
      'exclamation',
      'info-circle',
      'info',
      'minus',
      'plus',
      'question-circle',
      'question',
      'warning'
    ]
  }
]
